--COUNTRY TABLE
CREATE TABLE country
(
    id        bigint generated by default as identity primary key,
    name      VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);

-- AUTHOR TABLE
CREATE TABLE author
(
    id         bigint generated by default as identity primary key,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT REFERENCES country (id)
);

--BOOK TABLE
CREATE TABLE book
(
    id               bigint generated by default as identity primary key,
    name             VARCHAR(255) NOT NULL,
    category         VARCHAR(255) NOT NULL,
    author_id        BIGINT REFERENCES author (id),
    available_copies INT,
    is_deleted       BOOLEAN DEFAULT FALSE,
    date_created     TIMESTAMP
);

-- USER TABLE (book_users)
CREATE TABLE book_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255) NOT NULL,
    name                       VARCHAR(255) NOT NULL,
    surname                    VARCHAR(255) NOT NULL,
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       VARCHAR(255)
);

-- WISHLIST TABLE
CREATE TABLE wishlist
(
    id              bigint generated by default as identity primary key,
    date            TIMESTAMP,
    user_username   VARCHAR(255),
    wishlist_status VARCHAR(255),
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_username) REFERENCES book_users (username)
);

-- JOIN TABLE FOR wishlist_books (ManyToMany)
CREATE TABLE wishlist_books
(
    wishlist_id BIGINT REFERENCES wishlist (id),
    book_id     BIGINT REFERENCES book (id),
    PRIMARY KEY (wishlist_id, book_id)
);